language: r

sudo: false
cache: packages
warnings_are_errors: false


before_install:
  - tlmgr install standalone showexpl imakeidx xpatch pgf

install:
  - openssl aes-256-cbc -K $encrypted_edff7f8e0b40_key -iv $encrypted_edff7f8e0b40_iv -in tools/deploy_key.enc -out .deploy_key -d
  - chmod 600 .deploy_key
  - eval `ssh-agent -s`
  - ssh-add .deploy_key

script: make manual-git

after_success: tools/deploy.sh

notifications:
  email: false

